[package]
name = "sclone"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version="3.0.0-beta.5", features=["derive"]}
execute = "0.2.9"
fs_extra = "1.2.0"